### ISSUE TITLE
TypeScript files support

### ISSUE THREAD

**Issue by koladev32** [okobsamoht/grcf#1]
Hi and thanks for the hard work. 
Is a TypeScript support feature on road?

**Comment by okobsamoht** [comment]
Hi Kola!
I apologize for the delay...
Yes TypeScript support is planned

- class component JS / TS
- functional component TS

**Comment by okobsamoht** [comment]
Good news :partying_face: 
the support of typescript have been addes.
add the option -tsx to generate a typscript component
